---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "Copy compiled backend app"
  become: true
  copy:
    src: ~/project/backend
    dest: /home/ubuntu

- name: "Build artifact"
  become: yes
  shell: |
    cd backend
    npm install
    npm run migrations
    pm2 start --name "backend" npm -- start